spring.application.name=email
server.port=8002

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tzyudistira@gmail.com
# Gunakan App Password (16 digit) jika menggunakan Gmail
spring.mail.password=etqexocuidregqdn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true